version: "3"
services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - .:/opt/app/api
  postgres:
    build:
      context: ./local/postgres
      dockerfile: Dockerfile
      args:
        - POSTGRES_DB=${POSTGRES_DB:-postgres}
        - POSTGRES_USER=${POSTGRES_USER:-postgres}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
    container_name: postgres
    restart: "no"
    volumes:
      - ./local/postgres/data:/var/lib/postgresql/data
    ports:
      - "9920:9920"
    networks:
      - dev-local
networks:
  dev-local:
