#!/bin/bash

if [ -f .env ]; then
  source .env
else
  echo ".env file not found"
  exit 1
fi

docker run --rm \
  -e ENV_RUN_MODE="$ENV_RUN_MODE" \
  -e ENV_POSTGRES_HOST="$ENV_POSTGRES_HOST" \
  -e ENV_POSTGRES_USER="$ENV_POSTGRES_USER" \
  -e ENV_POSTGRES_PASSWORD="$ENV_POSTGRES_PASSWORD" \
  -e ENV_POSTGRES_NAME="$ENV_POSTGRES_NAME" \
  -e ENV_POSTGRES_PORT="$ENV_POSTGRES_PORT" \
  -e ENV_POSTGRES_SSL_MODE="$ENV_POSTGRES_SSL_MODE" \
  -e ENV_POSTGRES_TIME_ZONE="$ENV_POSTGRES_TIME_ZONE" \
  -e ENV_POSTGRES_DATA_SOURCE_NAME="$ENV_POSTGRES_DATA_SOURCE_NAME" \
  -e ENV_POSTGRES_BATCH_CREATE_SIZE="$ENV_POSTGRES_BATCH_CREATE_SIZE" \
  -e ENV_AWS_ACCESS_KEY_ID="$ENV_AWS_ACCESS_KEY_ID" \
  -e ENV_AWS_ACCESS_SECRET_KEY="$ENV_AWS_ACCESS_SECRET_KEY" \
  -e ENV_AWS_CREDENTIAL_TOKEN="$ENV_AWS_CREDENTIAL_TOKEN" \
  -e ENV_AWS_REGION="$ENV_AWS_REGION" \
  -e ENV_AWS_S3_BUCKET="$ENV_AWS_S3_BUCKET" \
  -e ENV_AWS_S3_PREFIX="$ENV_AWS_S3_PREFIX" \
  -e ENV_SERVICE_EMAIL="$ENV_SERVICE_EMAIL" \
  -e ENV_CORS_ORIGIN="$ENV_CORS_ORIGIN" \
  -e ENV_ALLOWED_METHODS="$ENV_ALLOWED_METHODS" \
  --network="host" \
  "$ENV_PROJECT_NAME" --filename "$1" --account "$2"
